# Generated by Django 6.0.6 on 2026-10-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "item", "verbose_name_plural": "items"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "status", "verbose_name_plural": "statuses"},
        ),
        migrations.AlterModelTable(
            name="item",
            table="items",
        ),
        migrations.AlterModelTable(
            name="status",
            table="statuses",
        ),
    ]
