# Generated by Django 6.0.6 on 2026-10-07 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_item_options_alter_status_options_and_more"),
        ("storefronts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="storefront",
            field=models.ForeignKey(
                default="ce44e7cf-d124-41b8-b09f-4fb765c4d645",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="storefronts.storefront",
            ),
            preserve_default=False,
        ),
    ]
