# Generated by Django 6.0.6 on 2026-10-07 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Storefront",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=225)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="storefronts/"),
                ),
            ],
            options={
                "verbose_name": "storefront",
                "verbose_name_plural": "storefronts",
                "db_table": "storefronts",
            },
        ),
    ]
