# Generated by Django 6.0.6 on 2026-09-30 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("place_id", models.CharField()),
                ("name", models.CharField()),
                ("city", models.CharField()),
                ("full_address", models.CharField()),
                ("region", models.CharField()),
                ("longitude", models.CharField()),
                ("latitude", models.CharField()),
            ],
        ),
    ]
