# Generated by Django 6.0.6 on 2026-09-30 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Craft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("craft_name", models.CharField(max_length=125, unique=True)),
            ],
            options={
                "verbose_name": "craft",
                "verbose_name_plural": "crafts",
                "db_table": "crafts",
            },
        ),
    ]
